### ISSUE TITLE
Rendering is slow

### ISSUE THREAD

**Issue by benjamw** [benjamw/tracers#3]
@Volcanic-Penguin 

Please test this on your machine again and see if the slowness has been fixed.

@erikwatson did some great work getting the code to use proper animation frames, and I fixed up the mirroring to do the same.

**Comment by Volcanic-Penguin** [comment]
Superb! Runs very nicely now! 

Erik is a friend of mine I made back in the Flash days on DeviantArt.

This is a really nice recreation of the old flash version. 

I think it would be really nice to have the hotkeys displayed in the web app itself so you don't need to look at the readme, or possibly even have buttons. Also it seems to be , and . to change line count not < and >  

Anyway awesome stuff!
